# Generated by Django 5.1 on 2024-12-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_created_producto_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='tienda/default_image.jpg', null=True, upload_to='tienda'),
        ),
    ]
