# Generated by Django 5.1 on 2025-11-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0004_alter_producto_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoriaprod",
            name="update",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="update",
        ),
        migrations.AddField(
            model_name="categoriaprod",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="categoriaprod",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
