# Generated by Django 5.1 on 2025-11-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_lineapedido_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineapedido",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="lineapedido",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
