# Generated by Django 5.1 on 2024-10-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notas',
            options={'verbose_name': 'nota', 'verbose_name_plural': 'notas'},
        ),
    ]
