# Generated by Django 5.1 on 2025-11-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0002_alter_notas_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoria",
            name="update",
        ),
        migrations.RemoveField(
            model_name="notas",
            name="update",
        ),
        migrations.AddField(
            model_name="categoria",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="notas",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="notas",
            name="contenido",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="notas",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
    ]
